### ISSUE TITLE
Should `getMentionsForPage` return all items in a `children` array?

### ISSUE THREAD

**Issue by paulrobertlloyd** [vandie/webmention-handler#21]
See https://jf2.spec.indieweb.org/#collections; I’m unsure if the object returned by `getMentionsForPage` is valid JF2 without the results being returned as an array under a top-level `children` property.

**Comment by vandie** [comment]
I think I see your confusion. This library is only an implementation of https://www.w3.org/TR/webmention/

It does not consider the JF2 serialisation standard which is still in a working draft state.

**Comment by paulrobertlloyd** [comment]
Ah, right. I am a little confused as there is some normalisation taking place (with authors, entries and cards returned as JF2 objects) 🤪 How much normalisation should be performed by this library?

**Comment by vandie** [comment]
While it may appear similar to jf2 at times, that's simply because JF2 is a nomalisation of the same form of microformat data. This library does minimal normalising aiming only to be internally consistant. There is probably an argument to be made that now that the JF2 standard is further along, that there should be a conversion.

**Comment by paulrobertlloyd** [comment]
Closing in favour of #20, which covers similar ground.
